# 需要修改成为自己的cutlass路径
set(CUTLASS_PATH "/home/lang/workspace/cutlass/include/")
set(CUTLASS_UTIL_PATH "/home/lang/workspace/cutlass/tools/util/include")
set(CUTLASS_NVCC_ARCHS 86)
set(CMAKE_CUDA_ARCHITECTURES 86)
set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} --expt-relaxed-constexpr")


add_executable(v1_native_gemm v1_native_gemm.cu)
target_link_libraries(v1_native_gemm PRIVATE CUDA::cudart ${CUDA_cublas_LIBRARY})
target_include_directories(v1_native_gemm PRIVATE ${CUTLASS_PATH} ${CUTLASS_UTIL_PATH})
if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    target_compile_options(v1_native_gemm PRIVATE  $<$<COMPILE_LANGUAGE:CUDA>:$<$<CONFIG:Debug>:-O0 -G>>)
else()
    target_compile_options(v1_native_gemm PRIVATE -lineinfo)
endif()

add_executable(v2_shared_memory v2_shared_memory.cu)
target_link_libraries(v2_shared_memory PRIVATE CUDA::cudart ${CUDA_cublas_LIBRARY})
target_include_directories(v2_shared_memory PRIVATE ${CUTLASS_PATH} ${CUTLASS_UTIL_PATH})
if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    target_compile_options(v2_shared_memory PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:-G>)
else()
    target_compile_options(v2_shared_memory PRIVATE -lineinfo)
endif()

add_executable(v3_epilogue v3_epilogue.cu)
target_link_libraries(v3_epilogue PRIVATE CUDA::cudart ${CUDA_cublas_LIBRARY})
target_include_directories(v3_epilogue PRIVATE ${CUTLASS_PATH} ${CUTLASS_UTIL_PATH})
if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    target_compile_options(v3_epilogue PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:-g -G>)
else()
    target_compile_options(v3_epilogue PRIVATE -lineinfo)
endif()
target_compile_options(v3_epilogue PRIVATE -O0)

add_executable(v4_multistage v4_multistage.cu)
target_link_libraries(v4_multistage PRIVATE CUDA::cudart ${CUDA_cublas_LIBRARY})
target_include_directories(v4_multistage PRIVATE ${CUTLASS_PATH} ${CUTLASS_UTIL_PATH})
if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    target_compile_options(v4_multistage PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:-g -G>)
else()
    target_compile_options(v4_multistage PRIVATE -lineinfo)
endif()
target_compile_options(v4_multistage PRIVATE -O0)