add_executable(gemm_softmax gemm_softmax.cu)
target_link_libraries(gemm_softmax PRIVATE CUDA::cudart ${CUDA_cublas_LIBRARY})
target_include_directories(gemm_softmax PRIVATE ${CUTLASS_PATH} ${CUTLASS_UTIL_PATH} ${CMAKE_CURRENT_SOURCE_DIR}/../common)
if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    target_compile_options(gemm_softmax PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:-g -G>)
else()
    target_compile_options(gemm_softmax PRIVATE -lineinfo)
endif()
target_compile_options(gemm_softmax PRIVATE -O0)